### ISSUE TITLE
No anndata to other format conversion 

### ISSUE THREAD

**Issue by likejie** [cellgeni/sceasy#11]
I would like to test anndata to seurat conversion by calling convertFormat function. But it turned out there is no "from anndata" option. Did i miss anything?  

Thanks a lot!

convertFormat
function (obj, from = c("seurat", "sce", "loom"), to = c("anndata",
    "loom", "sce"), outFile = NULL, main_layer = NULL, ...)
{
    from <- match.arg(from)
    to <- match.arg(to)
    tryCatch({
        func <- eval(parse(text = paste(from, to, sep = "2")))
    }, error = function(e) {
        stop(paste0("Unsupported conversion from \"", from, "\" to \"",
            to, "\""), call. = FALSE)
    }, finally = {
    })
    return(func(obj, outFile = outFile, main_layer = main_layer,
        ...))
}

**Comment by sonejilab** [comment]
Same here:
Error in match.arg(from) : 'arg' should be one of “seurat”, “sce”, “loom”

It would be great to know if conversion from h5ad to seurat is possible.

**Comment by cshasha** [comment]
Hi -- any updates to this?

**Comment by nh3** [comment]
Sorry for getting back to you late. The functionality was implemented but not enabled in convertFormat(). It was fixed in #10 . Please try again with the github version.

**Comment by bschilder** [comment]
The error still seems to come up (in this case anndata -> sce):
